### ISSUE TITLE
Initial setup and missing requirements

### ISSUE THREAD

**Issue by renepardon** [42coders/the-laravel-admin-panel#5] opened 2021-12-18 17:44 UTC
Hi @Max-Hutschenreiter 

I just wanted to give this a try but I figured out it doesn't work on a plain new Laravel installation. (created with `laravel new`)
After installing the missing requirement e.g. **laravel/ui** I was able to authenticate to the admin panel and saw the users already on the left column. BUT as soon as I click on the users nav item, I receive the next error:

`SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "FROM" LINE 1: SHOW COLUMNS FROM users ^ (SQL: SHOW COLUMNS FROM users) `

I use postgresql v14.1, PHP 8.1.0, laravel 8.65

**Comment by renepardon** [comment] 2021-12-18 18:28
Trying the whole thing with laravel sail and mariadb I receive the following error when accessing the user's datatables view:

> [2021-12-18 18:19:21] local.ERROR: Undefined array key "two_factor_secret" {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key \"two_factor_secret\" at /var/www/html/vendor/the42coders/the-laravel-admin-panel/src/Traits/TLAPAdminTrait.php:238)

**Comment by Max-Hutschenreiter** [comment] 2022-01-12 11:17
Regarding the PostgreSQL I am not sure what can cause it since I rely only on Eloquent features. I will try to test it someday. 

The bug for the two_factor_secret is fixed now. It was caused by the hidden fields jetstream/inertia is defined in the User Model. v.0.3.3

Thanks for the feedback :)

**Closed** 2022-01-12 11:17 UTC
